name: Slack PR Notify
on:
  pull_request:
    types: [opened, ready_for_review]
jobs:
  notify:
    if: >-
      github.event.pull_request.draft == false &&
      github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      contents: read
      pull-requests: read
    uses: progressionlive/actions/.github/workflows/slack-pr-notify.yml@master
    secrets:
      SLACK_CLI_TOKEN: ${{ secrets.SLACK_CLI_TOKEN }}
